# bootstrap-build.ps1
#
# One-time setup + recovery for the Crowpanel 7" P4 ha_autopanel
# build environment. Idempotent - safe to run any time. Exits 0
# on success, 1 on failure with a clear message.
#
# What this fixes:
#   * `fatal: not a git repository` in the IDF dep resolution
#     step when C:/esphome_tdd/.git is missing (e.g. after a
#     destructive clean-all, a new box, or a fresh checkout).
#   * The build path was placed outside the project on purpose
#     (short paths avoid the 32k linker CreateProcess limit on
#     Windows) - so the build dir has to BE a git repo, not just
#     sit inside one.
#
# What this does NOT do (and you should NOT do by hand):
#   * rm -rf the build dir
#   * edit CMakeLists.txt / sdkconfig / partition files in
#     C:/esphome_tdd - those are auto-generated by ESPHome
#   * git init C:/esphome_tdd repeatedly - one init is enough
#
# Normal workflow (PowerShell, from this dir):
#
#   PS> esphome compile test_dynamic_component.yaml --device COM47
#   PS> esphome upload  test_dynamic_component.yaml --device COM47
#   PS> esphome logs    test_dynamic_component.yaml --device COM47
#
# If a build fails:
#   1. esphome clean  test_dynamic_component.yaml
#   2. retry
#   3. if still failing: esphome clean-all test_dynamic_component.yaml
#   4. retry
#   5. if STILL failing (esp. the "fatal: not a git repository"
#      error in dep resolution): run THIS script, then retry.
#

$ErrorActionPreference = 'Stop'

$BuildPath = 'C:/esphome_tdd'
$ProjectRoot = $PSScriptRoot

function Write-Step($msg) {
    Write-Host "[bootstrap] $msg" -ForegroundColor Cyan
}

function Write-Ok($msg) {
    Write-Host "[bootstrap] OK  $msg" -ForegroundColor Green
}

function Write-Warn($msg) {
    Write-Host "[bootstrap] WARN  $msg" -ForegroundColor Yellow
}

function Write-Fail($msg) {
    Write-Host "[bootstrap] FAIL  $msg" -ForegroundColor Red
}

# --- 1. Sanity: this script is meant to run from the project dir ---

if (-not (Test-Path (Join-Path $ProjectRoot 'test_dynamic_component.yaml'))) {
    Write-Fail "Run this from the Crowpanel project root:"
    Write-Fail "  C:\ESPHome_Projects\Crowpanel_7.00_ESP32-P4"
    exit 1
}

# --- 2. Ensure the build dir exists ---

if (-not (Test-Path $BuildPath)) {
    Write-Step "Creating $BuildPath"
    New-Item -ItemType Directory -Path $BuildPath -Force | Out-Null
}

# --- 3. Ensure the build dir is a git repo ---

$GitDir = Join-Path $BuildPath '.git'
if (-not (Test-Path $GitDir)) {
    Write-Step "Initializing $BuildPath as a git repo (one-time)"
    Push-Location $BuildPath
    try {
        git init -q
        if ($LASTEXITCODE -ne 0) { throw "git init failed" }
        # Use --initial-branch to avoid the "master"/"main" warning
        git checkout -q -b master 2>$null
        git config user.email 'troy@local' 2>$null
        git config user.name  'Troy'        2>$null
    } finally {
        Pop-Location
    }
    Write-Ok "$BuildPath is now a git repo"
} else {
    Write-Ok "$BuildPath already a git repo (.git exists)"
}

# --- 4. Ensure .gitignore is in place ---

$Gitignore = Join-Path $BuildPath '.gitignore'
$Marker    = '# bootstrap-build.ps1 managed'

if (-not (Test-Path $Gitignore) -or -not (Select-String -Path $Gitignore -SimpleMatch $Marker -Quiet)) {
    Write-Step "Writing $Gitignore"
    @"
$Marker
# Ignore EVERYTHING in this dir by default. This is ESPHome's
# build dir - all output is auto-generated. The only things we
# preserve are:
#   1. .git (so the IDF's `git rev-parse` works for dep resolution)
#   2. This .gitignore (so future "git add -A" doesn't add the
#      world, blowing up the .git size and slowing builds)
#   3. README.txt (so future humans/me know not to touch anything)
# See ./bootstrap-build.ps1 (one level up, in the Crowpanel
# project) for the one-time setup that created this repo. Once
# the .git dir is here, NEVER delete it - the IDF component
# manager requires this dir to be a git work-tree.
*
!.gitignore
!.git
!README.txt
"@ | Set-Content -Path $Gitignore -Encoding UTF8
    Write-Ok ".gitignore in place"
} else {
    Write-Ok ".gitignore already in place"
}

# --- 5. Initial commit (only if there are no commits yet) ---

Push-Location $BuildPath
try {
    $hasCommits = (git rev-parse --verify HEAD 2>$null)
    if (-not $hasCommits) {
        Write-Step "Creating initial empty commit so `git rev-parse HEAD` succeeds"
        git add .gitignore README.txt 2>$null
        git commit -q -m 'build dir initial commit (do not touch)' 2>$null
        Write-Ok "initial commit on master"
    } else {
        Write-Ok "HEAD = $hasCommits"
    }
} finally {
    Pop-Location
}

# --- 6. Sanity check: `git rev-parse` from inside the build dir ---

$probe = (git -C $BuildPath rev-parse --is-inside-work-tree 2>$null)
if ($probe -ne 'true') {
    Write-Fail "git rev-parse still fails inside $BuildPath"
    Write-Fail "Manual recovery: cd $BuildPath ; git init ; git commit --allow-empty -m init"
    exit 1
}
Write-Ok "git rev-parse works in $BuildPath"

# --- 7. Remind the user about Git Bash ---

if ($env:MSYSTEM -or $env:MSYS) {
    Write-Warn "You're in Git Bash / MSYS - use a regular PowerShell for builds"
    Write-Warn "  (the IDF's idf_tools.py refuses to run under MSYS)"
}

# --- 8. Done ---

Write-Host ""
Write-Host "[bootstrap] Done. Build with:" -ForegroundColor Green
Write-Host "  esphome compile test_dynamic_component.yaml --device COM47" -ForegroundColor Green
Write-Host ""
exit 0
